eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5

spring:
  application:
    name: Order-Service
  data:
    mongodb:
      database: order_db
      host: localhost
      port: 27017
      repositories:
        enabled: true

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379
    expiration: 500

  cloud:
      stream:
        bindings:
          customerChannel:
            destination: exchange
            group: customer-queue
        default:
          contentType: application/json
        rabbit:
          bindings:
            customerChannel:
              consumer:
                bindingRoutingKey: customer-queue
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

server:
  port: 8081